config/routes.rb
Zonazero::Application.routes.draw do
  
  mount Mercury::Engine => '/'

  resources :messages
  

  resources :awards
  resources :works
  resources :clients

  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
  match '/kit',       to: 'static_pages#kit'
  match '/order',     to: 'static_pages#order' 
  
  
  root :to => 'works#home'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  
    get ':id', to: 'pages#show', as: :page
  
  resources :pages do
    member { post :mercury_update }
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :description, :logo1, :title, :year, :year1, :description1, :year2, :description2, :year3, :description3
  
    has_attached_file :logo1, :styles => { :small => "100x100#" }

  validates_attachment_size :logo1, :less_than => 5.megabytes
  validates_attachment_content_type :logo1, :content_type => ['image/jpeg', 'image/png']
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  has_many :options
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :title, :logo1, :logo2, :point1, :point2, :point3, :point4, :point5
                  
    
  has_attached_file :logo1, :styles => { :small => "100x100>" }

  has_attached_file :logo2, :styles => { :big => "260x80>" }


validates_attachment_size :logo1, :less_than => 5.megabytes
validates_attachment_content_type :logo1, :content_type => ['image/jpeg', 'image/png']
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :name, :company, :position, :pre, :tel, :mail, :comment, :option_ids
  
  has_many :messageoptions
  has_many :options, through: :messageoptions
  
  
end

app/models/messageoption.rb
class Messageoption < ActiveRecord::Base
  belongs_to :option
  belongs_to :message
end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :title, :category_id
  belongs_to :category
  has_many :messageoptions
  has_many :messages, through: :messageoptions
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :description, :title
  extend FriendlyId
  friendly_id :title, :use => [:slugged, :history]
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :description, :logo1, :logo2, :title, :front_show, :front_title, :delete_logo1, :delete_logo2, :sn
  
  
  
    has_attached_file :logo1, :styles => { :small => "138x138#" }

    has_attached_file :logo2, :styles => { :small => "138x138#", :big => "940x906#" }


  validates_attachment_size :logo1, :less_than => 5.megabytes
  validates_attachment_content_type :logo1, :content_type => ['image/jpeg', 'image/png']
  validates_attachment_size :logo2, :less_than => 5.megabytes
  validates_attachment_content_type :logo2, :content_type => ['image/jpeg', 'image/png']
  
  before_validation :clear_logo1
  before_validation :clear_logo2

  
  def delete_logo1=(value)
     @delete_logo1 = !value.to_i.zero?
   end

   def delete_logo1
     !!@delete_logo1
   end
   alias_method :delete_logo1?, :delete_logo1
   
   def clear_logo1
     self.logo1 = nil if delete_logo1? && !logo1.dirty?
   end
   
 def delete_logo2=(value)
    @delete_logo2 = !value.to_i.zero?
  end

  def delete_logo2
    !!@delete_logo2
  end
  alias_method :delete_logo2?, :delete_logo2

  def clear_logo2
    self.logo2 = nil if delete_logo2? && !logo2.dirty?
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  #before_filter :miniprofiler
  
  # private
  # def miniprofiler
  #   if admin_user_signed_in?
  #   logger.info 'Profiling'
  #   Rack::MiniProfiler.authorize_request
  #   # Rack::MiniProfiler.config.storage = Rack::MiniProfiler::MemoryStore
  #   end
  # end
    
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # GET /awards
  # GET /awards.json
  def index
    @message = Message.new
    @awards = Award.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @message = Message.new
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < InheritedResources::Base
   def index
      @messages = Message.where(:check => true).all
    end

    def show
      @message = Message.find(params[:id])
    end

    def new
      @message = Message.new
    end

    def edit
      @message = Message.find(params[:id])
    end

    def create
      @message = Message.new(params[:message])
       if @message.save
          RequestMailer.new_message(@message).deliver
          redirect_to(:back)
        else
          render :new
        end

    end

    # PUT /messages/1
    # PUT /messages/1.json
    def update
      @message = Message.find(params[:id])

      respond_to do |format|
        if @message.update_attributes(params[:message])
          format.html { redirect_to @message }
          format.json { head :no_content }
          flash[:notice] = t('message_updated')
        else
          format.html { render action: "edit" }
          format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /messages/1
    # DELETE /messages/1.json
    def destroy
      @message = Message.find(params[:id])
      @message.destroy

      respond_to do |format|
        format.html { redirect_to messages_url }
        format.json { head :no_content }
      end
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
    @page = Page.first
    @message = Message.new
  end

  def show
    @message = Message.new
    @pages = Page.all
    @page = Page.find(params[:id])
  end
  
  def mercury_update
    page = Page.find(params[:id])
    page.title = params[:content][:page_title][:value]
    page.description = params[:content][:page_description][:value]
    page.save!
    render text: ""
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
    @message = Message.new
  end

  def kit
    @message = Message.new
  end

  def contact
    @message = Message.new
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.order("sn ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  def show
    @message = Message.new
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end
  
  def home
    @message = Message.new
    
    @front_works = Work.where(:front_show => true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
     controller.include?(params[:controller])
   end

   def action?(*action)
     action.include?(params[:action])
   end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/awards/index.html.erb
<body>
	<div id="container">
		<%= render 'layouts/header' %>
		<div id="middle">
			<div id="left">
	
			</div>

			<div id="right">
				<div class="h1">
					<h1>Награды</h1>
				</div>
				<ul class="awards-block">
					<% @awards.each do |award| %>
					<li>
						<div class="award-item">
							<span class="ab-img">
								<%= image_tag(award.logo1.url(:small)) %>		
							</span>
							<p><%= award.title %></p>
							<span class="ab-show-link"><span>Показать награды</span></span>
						</div>
						<div class="award-detail">
							<dl>
								<dt><%= award.year %></dt>
								<dd><%= award.description %></dd>
								<dt><%= award.year1 %></dt>
								<dd><%= award.description1 %></dd>
								<dt><%= award.year2 %></dt>
								<dd><%= award.description2 %></dd>
								
							</dl>

							<a href="#" class="ad-close">скрыть</a>
							<span class="ab-img-wall"></span>
						</div>
					</li>
					<% end %>
				</ul>
				
			</div>
		</div>
		
		<div class="footer-space"></div>
	</div>
	
	<%= render 'layouts/footer' %>

app/views/clients/index.html.erb
	<div id="container">
		<%= render 'layouts/header' %>
		
		<div id="middle">
      <%= render 'shared/left_menu' %>

			<div id="right">
				<div class="h1">
					<h1>наши клиенты</h1><span class="h1-notice">(нажмите на логотип, чтобы посмотреть список работ)</span>
				</div>
					
				<ul class="clients-list">
					<% @clients.each do |client| %>
					<li>
						<div>
							<img src="<%= client.logo2 %>" width="260" height="80" alt="client-3">
							<span class="cl-title"><%= client.title %></span>
							<ul>
								<li><%= client.point1 %></li>
								<li><%= client.point2 %></li>
								<li><%= client.point3 %></li>
								<li><%= client.point4 %></li>
								<li><%= client.point5 %></li>
							</ul>
							<a href="#" class="cl-switch">скрыть</a>
						</div>
						<a href="#"><img src="<%= client.logo1 %>" width="100" height="100" alt="client-1" style="margin-top: -33px"></a>
					</li>
					<% end %>
					</ul>
			</div>
		</div>
		
		<div class="footer-space"></div>
	</div>
	<%= render 'layouts/footer' %>

app/views/messages/_form.html.erb
<div class="order-block" id="order-block">
<%= form_for(@message) do |f| %>
	<ul>
		<li>
			<label>Имя:</label>
			<%= f.text_field :name %>
		</li>
		
		<li>
			<label>Компания:</label>
			<%= f.text_field :company %>
		</li>
		
		<li>
			<label>Должность:</label>
			<%= f.text_field :position %>
		</li>
		
		<li>
			<label>Телефон:</label>
			<div class="ob-answer ob-phone">
				<p>( <%= f.text_field :pre, :class=>'p-code' %> ) <%= f.text_field :tel, :class=>'p-number' %><a href="#" title="Удалить" class="p-remove">Удалить</a><a href="#" title="Добавить" class="p-add">Добавить</a></p>
			</div>
		</li>
		
		<li>
			<label>Эл. почта:</label>
			<%= f.text_field :mail %>
		</li>
		
		<li>
			<label>Чем интересуетесь:</label>
			<div class="ob-answer ob-interest">
				<% Category.all.each do |category| %>
				<p><a href="#"><%= category.title %></a></p>
				<div class="oba-sub">
				    <% Option.where(:category_id => category.id).each do |option| %>
				      <p><%= check_box_tag "message[option_ids][]", option.id %>
				      <%= label_tag dom_id(option), option.title %></p>
				    <% end %>
				</div>
				<% end %>
			</div>
		</li>
		
		<li>
			<label>Примечания:</label>
			<textarea></textarea>
		</li>
		
		<li>
			<label>Хотели бы получить ответ, содержащий:</label>
			<div class="ob-answer">
				<p><input type="checkbox" id="1" /><label for="1">Прайс-лист на указанные услуги</label></p>
				<p><input type="checkbox" id="2" /><label for="2">Презентации проектов</label></p>
				<p><input type="checkbox" id="3" /><label for="3">Референс-лист</label></p>
				<p><input type="checkbox" id="4" /><label for="4">Краткую справку об агентстве</label></p>
			</div>
		</li>
		
		<li>
			<label>Откуда вы узнали о ZERO?:</label>
			<div class="ob-answer oba-zero">
				<p><input type="checkbox" id="5" /><label for="5">Рекомендация</label></p>
				<p><input type="checkbox" id="6" /><label for="6">Публикация в СМИ</label></p>
				<p><input type="checkbox" id="7" /><label for="7">Справочник</label></p>
				<p><input type="checkbox" id="8" /><label for="8">Поиск в интернете</label></p>
				<p><input type="checkbox" id="9" /><label for="9">Отраслевое мероприятие</label></p>
			</div>
		</li>
		<li>
			<label>&nbsp;</label>
			<div class="ob-answer">
				<a href="#" class="ob-submit" tabindex="1" rel="nofollow">Отправить запрос</a>
			</div>
		</li>
	</ul>
</form>
<% end %>
	<a href="index.html" class="logo" title="На главную">ZERO b2b communications agency</a>
	<a href="#" class="ob-close"><span>Заказать</span></a>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.name %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @message.name %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/works/home.html.erb
<body class="index-tpl">
	<div id="container">
		<div id="header">
			<div class="header-ins">
			<%= link_to "На главную", root_path, class: "logo" %>

			<ul>
				<li>
					<%= link_to "компания", about_path %>
					<ul>
						<li><%= link_to "про зеро", about_path %></li>
						<li><%= link_to "клиенты", clients_path %></li>
					</ul>
				</li>
				<li><%= link_to "Работы", works_path %></li>
				<li><%= link_to "Награды", awards_path %></li>
				<li><%= link_to (contact_path) do %>
					<span>Контакты</span>
					<% end %></li>
				<li><a href="#" class="order-link"><span>Заказать</span></a></li>
			</ul>
			</div>
		</div>
		
		<div id="slider-idx">
			<ul>
				<% @front_works.each do |work| %>
				<li>
					<img src="img/px.gif" style="background: url(<%= work.logo2 %>) no-repeat center top;">
					<div class="sit-wrap"><span class="si-title"><%= work.front_title %></span></div>
					<a href="<%= url_for work %>" class="si-detail"><span>Перейти<br />к проекту</span></a>
				</li>
				<% end %>
			</ul>
			
			<div id="paging"  class="si-links"></div>
			<div class="slider-arrows">
				<a href="#" id="si-prev" class="si-arrows" title="Назад">Назад</a>
				<a href="#" id="si-next" class="si-arrows" title="Вперед">Вперед</a>
			</div>
		</div>
		
		<div class="footer-space"></div>
	</div>
	
	<%= render 'layouts/footer' %>

app/views/works/index.html.erb
<body>
	<div id="container">
		<%= render 'layouts/header' %>	
		<div id="middle">
			<div class="h1 wl-h1">
				<h1>Избранные работы</h1>
			</div>
					
			<ul class="works-list">
				<% @works.each do |work| %>
				<li>
					<%= link_to (work) do %>
					<span class="wl-img">
						<%= image_tag(work.logo1) %>
					</span>
						<%= work.title %>
						<span class="wl-brd"></span>
					<% end %>
				</li>
				<% end %>
			</ul>
		</div>
		
		<div class="footer-space"></div>
	</div>
	
	<%= render 'layouts/footer' %>

app/views/works/show.html.erb
<body>
	<div id="container">
		<%= render 'layouts/header' %>
		<div id="middle">
			<div id="left">
				<ul class="l-menu l-work-menu">	
					<li><%= link_to "назад", 'javascript:history.back()' %></li>
				</ul>
			</div>

			<div id="right" class="work-block">
				<div class="h1">
					<h1><%= @work.title %></h1>
				</div>
					
				<div class="content">
					<p><%= sanitize @work.description %></p>
				</div>
			</div>
		</div>
		<a href="#" title="Наверх" class="up-link">Наверх</a>
		
		<div class="footer-space"></div>
	</div>
	
	<%= render 'layouts/footer' %>