config/routes.rb
Zonazero::Application.routes.draw do
  
  mount Mercury::Engine => '/'

  resources :messages
  

  resources :awards
  resources :works
  resources :clients

  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
  match '/kit',       to: 'static_pages#kit'
  match '/order',     to: 'static_pages#order' 
  
  
  root :to => 'works#home'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  
    get ':id', to: 'pages#show', as: :page
  
  resources :pages do
    member { post :mercury_update }
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :description, :logo1, :title, :year, :year1, :description1, :year2, :description2, :year3, :description3
  
    has_attached_file :logo1, :styles => { :small => "100x100#" }

  validates_attachment_size :logo1, :less_than => 5.megabytes
  validates_attachment_content_type :logo1, :content_type => ['image/jpeg', 'image/png']
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  has_many :options
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :title, :logo1, :logo2, :point1, :point2, :point3, :point4, :point5
                  
    
  has_attached_file :logo1, :styles => { :small => "100x100>" }

  has_attached_file :logo2, :styles => { :big => "260x80>" }


validates_attachment_size :logo1, :less_than => 5.megabytes
validates_attachment_content_type :logo1, :content_type => ['image/jpeg', 'image/png']
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :name, :company, :position, :pre, :tel, :mail, :comment, :option_ids
  
  has_many :messageoptions
  has_many :options, through: :messageoptions
  
  
end

app/models/messageoption.rb
class Messageoption < ActiveRecord::Base
  belongs_to :option
  belongs_to :message
end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :title, :category_id
  belongs_to :category
  has_many :messageoptions
  has_many :messages, through: :messageoptions
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :description, :title
  extend FriendlyId
  friendly_id :title, :use => [:slugged, :history]
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :description, :logo1, :logo2, :title, :front_show, :front_title, :delete_logo1, :delete_logo2, :sn
  
  
  
    has_attached_file :logo1, :styles => { :small => "138x138#" }

    has_attached_file :logo2, :styles => { :small => "138x138#", :big => "940x906#" }


  validates_attachment_size :logo1, :less_than => 5.megabytes
  validates_attachment_content_type :logo1, :content_type => ['image/jpeg', 'image/png']
  validates_attachment_size :logo2, :less_than => 5.megabytes
  validates_attachment_content_type :logo2, :content_type => ['image/jpeg', 'image/png']
  
  before_validation :clear_logo1
  before_validation :clear_logo2

  
  def delete_logo1=(value)
     @delete_logo1 = !value.to_i.zero?
   end

   def delete_logo1
     !!@delete_logo1
   end
   alias_method :delete_logo1?, :delete_logo1
   
   def clear_logo1
     self.logo1 = nil if delete_logo1? && !logo1.dirty?
   end
   
 def delete_logo2=(value)
    @delete_logo2 = !value.to_i.zero?
  end

  def delete_logo2
    !!@delete_logo2
  end
  alias_method :delete_logo2?, :delete_logo2

  def clear_logo2
    self.logo2 = nil if delete_logo2? && !logo2.dirty?
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  #before_filter :miniprofiler
  
  # private
  # def miniprofiler
  #   if admin_user_signed_in?
  #   logger.info 'Profiling'
  #   Rack::MiniProfiler.authorize_request
  #   # Rack::MiniProfiler.config.storage = Rack::MiniProfiler::MemoryStore
  #   end
  # end
    
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # GET /awards
  # GET /awards.json
  def index
    @message = Message.new
    @awards = Award.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @message = Message.new
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < InheritedResources::Base
   def index
      @messages = Message.where(:check => true).all
    end

    def show
      @message = Message.find(params[:id])
    end

    def new
      @message = Message.new
    end

    def edit
      @message = Message.find(params[:id])
    end

    def create
      @message = Message.new(params[:message])
       if @message.save
          RequestMailer.new_message(@message).deliver
          redirect_to(:back)
        else
          render :new
        end

    end

    # PUT /messages/1
    # PUT /messages/1.json
    def update
      @message = Message.find(params[:id])

      respond_to do |format|
        if @message.update_attributes(params[:message])
          format.html { redirect_to @message }
          format.json { head :no_content }
          flash[:notice] = t('message_updated')
        else
          format.html { render action: "edit" }
          format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /messages/1
    # DELETE /messages/1.json
    def destroy
      @message = Message.find(params[:id])
      @message.destroy

      respond_to do |format|
        format.html { redirect_to messages_url }
        format.json { head :no_content }
      end
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
    @page = Page.first
    @message = Message.new
  end

  def show
    @message = Message.new
    @pages = Page.all
    @page = Page.find(params[:id])
  end
  
  def mercury_update
    page = Page.find(params[:id])
    page.title = params[:content][:page_title][:value]
    page.description = params[:content][:page_description][:value]
    page.save!
    render text: ""
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
    @message = Message.new
  end

  def kit
    @message = Message.new
  end

  def contact
    @message = Message.new
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.order("sn ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  def show
    @message = Message.new
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end
  
  def home
    @message = Message.new
    
    @front_works = Work.where(:front_show => true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
     controller.include?(params[:controller])
   end

   def action?(*action)
     action.include?(params[:action])
   end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="footer-ins">
		<div class="f-menu">
			<span class="f-title">Разделы</span>
			<ul>
				<li><%= link_to "компания", pages_path %></li>
				<li><%= link_to "работы", works_path %></li>
				<li><%= link_to "награды", awards_path %></li>
				<li><%= link_to "контакты", contact_path %></li>
			</ul>
		</div>
		
		<ul class="f-social">
			<li class="vk"><a href="#" title="Вконтакте">Вконтакте</a></li>
			<li class="tw"><a href="#" title="Twitter">Twitter</a></li>
			<li class="fb"><a href="#" title="Facebook">Facebook</a></li>
			<li class="in"><a href="#" title="LinkedIn">LinkedIn</a></li>
		</ul>
		
		<div class="f-who">
			<span class="f-title">Кто мы?</span>
			<p>Мы осуществляем маркетинговый консалтинг для компаний b2b-рынка. Это предполагает разработку и реали-<br />зацию полноценной программы инте-<br />грированных маркетинговых коммуни-<br />каций или отдельных ее элементов.</p>
		</div>
	
		<div class="f-contacts">
			<span class="f-title">Адрес</span>
			<p>118108, Санкт-Петербург,<br />ул. Достоевского, 44Е<br />+7 (812) 600-21-79<br /><a href="#">office@zonazero.ru</a></p>
		</div>	
	</div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	
	
	<%= link_to "На главную", root_path, class: "logo" %>
	
	<ul>
		<%= content_tag :li, :class => ('active' if action?("about"))  do %>
			<%= link_to "компания", about_path %>
			<ul>
				<li><%= link_to "про зеро", about_path %></li>
				<li><%= link_to "клиенты", clients_path %></li>
			</ul>
		<% end %>
		<%= content_tag :li, :class => ('active' if controller?("works") && action?("index"))  do %>
		  <%= link_to "Работы", works_path %>
		<% end %>
		<%= content_tag :li, :class => ('active' if controller?("awards"))  do %>
		<%= link_to "Награды", awards_path %>
		<% end %>
		<li><%= link_to "Контакты", contact_path %></li>
		<li><a href="#" class="order-link"><span>Заказать</span></a></li>
	</ul>
</div>

app/views/layouts/_request.html.erb
<div class="order-block" id="order-block">
	<form name="order-form" id="order-form" method="POST" action="">
		<ul>
			<li>
				<label>Имя:</label>
				<input type="text" name="name">
			</li>
			
			<li>
				<label>Компания:</label>
				<input type="text" name="name">
			</li>
			
			<li>
				<label>Должность:</label>
				<input type="text" name="name">
			</li>
			
			<li>
				<label>Телефон:</label>
				<div class="ob-answer ob-phone">
					<p>( <input type="text" class="p-code"> ) <input type="text" class="p-number"><a href="#" title="Удалить" class="p-remove">Удалить</a><a href="#" title="Добавить" class="p-add">Добавить</a></p>
				</div>
			</li>
			
			<li>
				<label>Эл. почта:</label>
				<input type="text" name="name">
			</li>
			
			<li>
				<label>Чем интересуетесь:</label>
				<div class="ob-answer ob-interest">
					<p><a href="#">Маркетинговые коммуникации</a></p>
					<div class="oba-sub">
						<p><input type="checkbox" id="555" /><label for="555">Разработка промо-сайта</label></p>
						<p><input type="checkbox" id="666" /><label for="666">Разработка корпоративного сайта</label></p>
						<p><input type="checkbox" id="777" /><label for="777">Разработка интернет-магазина</label></p>
					</div>
					
					<p><a href="#">Дизайн</a></p>
					<div class="oba-sub">
						<p><input type="checkbox" id="5555" /><label for="5555">Разработка промо-сайта</label></p>
						<p><input type="checkbox" id="6666" /><label for="6666">Разработка корпоративного сайта</label></p>
						<p><input type="checkbox" id="7777" /><label for="7777">Разработка интернет-магазина</label></p>
					</div>
					
					<p><a href="#">Эвент-маркетинг</a></p>
					<div class="oba-sub">
						<p><input type="checkbox" id="55555" /><label for="55555">Разработка промо-сайта</label></p>
						<p><input type="checkbox" id="66666" /><label for="66666">Разработка корпоративного сайта</label></p>
						<p><input type="checkbox" id="77777" /><label for="77777">Разработка интернет-магазина</label></p>
					</div>
					
					<p><a href="#">Веб-проекты</a></p>
					<div class="oba-sub">
						<p><input type="checkbox" id="555555" /><label for="555555">Разработка промо-сайта</label></p>
						<p><input type="checkbox" id="666666" /><label for="666666">Разработка корпоративного сайта</label></p>
						<p><input type="checkbox" id="777777" /><label for="777777">Разработка интернет-магазина</label></p>
					</div>
					
					<p><a href="#">Комплексные решения</a></p>
					<div class="oba-sub">
						<p><input type="checkbox" id="5555555" /><label for="5555555">Разработка промо-сайта</label></p>
						<p><input type="checkbox" id="6666666" /><label for="6666666">Разработка корпоративного сайта</label></p>
						<p><input type="checkbox" id="7777777" /><label for="7777777">Разработка интернет-магазина</label></p>
					</div>
				</div>
			</li>
			
			<li>
				<label>Примечания:</label>
				<textarea></textarea>
			</li>
			
			<li>
				<label>Хотели бы получить ответ, содержащий:</label>
				<div class="ob-answer">
					<p><input type="checkbox" id="1" /><label for="1">Прайс-лист на указанные услуги</label></p>
					<p><input type="checkbox" id="2" /><label for="2">Презентации проектов</label></p>
					<p><input type="checkbox" id="3" /><label for="3">Референс-лист</label></p>
					<p><input type="checkbox" id="4" /><label for="4">Краткую справку об агентстве</label></p>
				</div>
			</li>
			
			<li>
				<label>Откуда вы узнали о ZERO?:</label>
				<div class="ob-answer oba-zero">
					<p><input type="checkbox" id="5" /><label for="5">Рекомендация</label></p>
					<p><input type="checkbox" id="6" /><label for="6">Публикация в СМИ</label></p>
					<p><input type="checkbox" id="7" /><label for="7">Справочник</label></p>
					<p><input type="checkbox" id="8" /><label for="8">Поиск в интернете</label></p>
					<p><input type="checkbox" id="9" /><label for="9">Отраслевое мероприятие</label></p>
				</div>
			</li>
			<li>
				<label>&nbsp;</label>
				<div class="ob-answer">
					<a href="#" class="ob-submit" tabindex="1" rel="nofollow">Отправить запрос</a>
				</div>
			</li>
		</ul>
	</form>
	
	<a href="index.html" class="logo" title="На главную">ZERO b2b communications agency</a>
	<a href="#" class="ob-close"><span>Заказать</span></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zonazero</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>

<%= yield %>
<%= render :partial => 'messages/form', :locals => { :@message => Message.new} %>
</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = "/pages/1/mercury_update";

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'POST', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<% provide(:title, 'ZERO | Про zero') %>

	<div id="container">
		<%= render 'layouts/header' %>
		<div id="middle">
			<div id="left">
				<ul class="l-menu">	
					<% @pages.each do |page| %>
					<%= content_tag :li, (link_to page.title, page), :class => ('active' if @page == page) %>
					<% end %>
					<li><%= link_to "клиенты", clients_path %></li>
				</ul>
			</div>

			<div id="right">
				<div class="h1">
					<h1><%= @page.title %></h1>
				</div>
					
				<div class="content">
					<%= sanitize @page.description %>
				</div>
			</div>
		</div>
		
		<div class="footer-space"></div>
	</div>
	
	<%= render 'layouts/footer' %>

app/views/pages/show.html.erb
<% provide(:title, 'ZERO | Про zero') %>

	<div id="container">
		<%= render 'layouts/header' %>
		<div id="middle">
			<div id="left">
				<ul class="l-menu">	
					<% @pages.each do |page| %>
					<%= content_tag :li, (link_to page.title, page), :class => ('active' if @page == page) %>
					<% end %>
					<li><%= link_to "клиенты", clients_path %></li>
				</ul>
			</div>

			<div id="right">
				<div class="h1">
					<h1><span id="page_title" data-mercury="full"><%= @page.title %></span></h1>
				</div>
					
				<div class="content">
					<div id="page_description" data-mercury="full">
					<%= @page.description.html_safe %>
					</div>
				</div>
				<% if admin_user_signed_in? %>
				<%= link_to "Редактировать страницу", "/editor" + request.path, id: "edit_link", data: {save_url: mercury_update_page_path(@page)} %>
				<% end %>
			</div>
		</div>
		
		<div class="footer-space"></div>
	</div>
	
	<%= render 'layouts/footer' %>

app/views/shared/_left_menu.html.erb
<div id="left">
	<ul class="l-menu">	
		<%= content_tag :li, :class => ('active' if action?("about"))  do %>
		  <%= link_to "про зеро", about_path %>
		<% end %>
		<%= content_tag :li, :class => ('active' if controller?("clients")) do %>
		  <%= link_to "клиенты", clients_path %>
		<% end %>
	</ul>
</div>